### ISSUE TITLE
Un consiglio

### ISSUE THREAD

**Issue by christiancabizza** [paiuolo/django-oscar-bookstore#1]
Ciao Paiuolo, 
sto sbirciando la tua applicazione "django-oscar-bookstore". 
Sto controllando il processo di pagamento, che mi sembra orientato più al mondo degli ebooks che a quello dei libri fisici: mi sapresti dire come è possibile personalizzarlo in modo tale che i soldi vengano scalati all'utente Paypal soltanto dopo che l'ordine è stato spedito?

Ti ringrazio,
Christian

**Comment by paiuolo** [comment]
Ciao Christian,
l'applicazione in questione è un'estensione di django-oscar (che sto usando in un progetto). L'intenzione è quella di creare un'aggiunta alle "Sandbox" di Oscar che funga da punto di partenza per un eCommerce orientato ai libri (appena trovo un momento vedo di caricare le ultime modifiche).
La soluzione al tuo problema sta nella personalizzazione dell'app django-oscar-paypal (purtroppo non molto aggiornata) incaricata di portare a termine il processo di checkout. 
Se l'ordine contiene delle "lines" di prodotti fisici puoi fare in modo che la pressione del tasto di conferma (una volta tornati da paypal) effettui l'operazione "DoExpressCheckout" con l'importo dei soli eBooks e connettere un segnale alla modifica dello stato dell'ordine da Dashboard (nel tuo caso "order sent") che effettui un'ulteriore "DoExpressCheckout" per l'importo restante.
Saluti!

**Comment by christiancabizza** [comment]
Anzitutto grazie infinite per la celere risposta. In realtà a me interesserebbe restringere momentaneamente il campo di funzionamento dello store ai soli prodotti fisici, ed evitare dunque che il denaro venga scalato dal conto dell'utente. Essendo io un "newbie" di Oscar Django mi sarebbe piaciuto capire quali devono essere gli eventi sovrascritti o implementati, e(MAGARI!) recuperare degli esempi di funzionamento in pre-auth con il pagamento legato soltanto all'azione dell'operatore in dashboard.

**Comment by christiancabizza** [comment]
Ciao!
Perdona il disturbo, sempre io. 
Volevo chiederti un paio di consigli per poter personalizzare la tua applicazione: 
1) Come è possibile - secondo te - aggiungere dei gadget che si possano in qualche modo "associare" all'acquisto di un libro? Mi servirebbe poter aggiungere cappellini, t-shirts, etc da poter eventualmente associare all'acquisto di un libro. Sembrerebbe che non sia possibile definire altre classi di prodotto derivate da AbstractProduct... 
2) Mi puoi spiegare che cosa sono i BookFormat?

Perdonami se uso la issue per chiederti questi consigli ma non ho un tuo contatto.

Grazie in anticipo.
C.

**Comment by paiuolo** [comment]
Riesco a rispondere solo ora,
1) Puoi creare una classe di prodotti "Gadget" e caricarvi i prodotti che intendi regalare.
Puoi crearne una promozione ad hoc che si attivi all'inserimento nel carrello di un prodotto appartenente ad un range (ad esempio prodotti con in regalo un cappellino). 
Per fare in modo che all'inserimento di un libro venga caricato nel carrello un gadget puoi alterare l'applicazione basket o partner (creando una strategy ad hoc).

2) I BookFormat sono i formati disponibili per ciascun libro. Servono per non dover creare classi diverse per libri digitali e cartacei e semplificare la logica di presentazione (un tasto di acquisto per ogni formato).

Con Oscar non è necessario definire classi derivate dalla classe prodotto. Puoi creare delle proprietà al momento della definizione di una categoria (ad esempio taglia o colore nel caso di una maglietta) e definirle al momento della creazione di un prodotto.

Ad ogni modo se intendi restringere la vendita ai soli prodotti fisici ti consiglio di usare direttamente Oscar ed adattarlo al tuo caso.

Buona fortuna!
